[h2o]
appid = "application-id"
secret = "application-secret"
index = "index.md?template=home"
admin = false
cache = false
default_limit_size = 20

[service]
object = true
file = true
auth = false
system = false

[event]
currency = 50

[session]
duration = "1h"

[auth]
	[auth.mobile]
	enable = true

	[auth.email]
	enable = true
	active = true

	[auth.qq]
	enable = true

	[auth.weibo]
	enable = true

[smtp]
host = "your smtp host"
port = 25
user = ""
password = ""
sender = "sender mailbox"
replyto = "reply mailbox"

[template]
markdown = "markdown.tpl"
regist = "regist.tpl"
forget = "forget.tpl"
active = "active.tpl"

[subject]
regist = "新用户注册通知"
forget = "用户密码重置"
active = "用户激活通知"

[third]	
	[third.qiniu]
	enable = false
	appid = "your qiniu appid"
	secret = "your qiniu secret"
	domain = ""
	bucket = ""

[log]
enable = true
filename = "logs/h2o.log"
level = "DEBUG"
rotate = true
rotate_daily = true
rotate_max_line = 0
rotate_max_size = 0


